version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app-db
      MYSQL_PASSWORD: 12345
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 4321
    networks:
      - mysql-phpmyadmin

#  minio:
#    image: minio/minio
#    ports:
#     - "9000:9000"
#     - "9001:9001"
#   volumes:
#     - minio_storage:/data
#    environment:
#      MINIO_ROOT_USER: masoud
#     MINIO_ROOT_PASSWORD: Strong#Pass#2022
#    command: server --console-address ":9001" /data

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
#  minio_storage: {}